spring:
  rabbitmq:
    addresses: 192.168.28.133:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    # 手工签收
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
      order:
        queue:
          name: queue-2
          durable: true
        exchange:
          name: exchange-2
          durable: true
          type: topic
          ignoreDeclarationExceptions: true
        key: springboot.*

